name: CI 6 0 53

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 6
      uses: actions/setup-java@v1
#      uses: joschi/setup-jdk@v2
      with:
        java-version: '6'

    - name: build java
      run: java -version
    
    - name: donwload ant 9
      run: curl https://downloads.apache.org/ant/binaries/apache-ant-1.9.15-bin.zip --output ant9.zip

    - name: unzip ant 9
      run: unzip ant9.zip

    - name: build Ant
      run: ant -version
