name: CI 6 0 53

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 6
      uses: actions/setup-java@v1
      with:
        java-version: '6'
    
    - name: donwload ant 9
      run: curl https://archive.apache.org/dist/ant/binaries/apache-ant-1.9.9-bin.zip --output ant9.zip

    - name: unzip ant 9
      run: unzip -qq ant9.zip

    - name: downgrate ant version to 1.9.9
      run:  sudo cp -a apache-ant-1.9.9/. $ANT_HOME

    - name: download libraries
      run: curl https://support-delivery.s3.amazonaws.com/tomcat6-build-libs-.zip --output tomcat6-build-libs-.zip
      
    - name: extract libs
      run: unzip -qq tomcat6-build-libs-.zip -d /home/runner/
    
    - name: ant_build
      run: ant

    - name: ant_test
#       id: ante_test_result
      run: ant test
    
    - if: failure()
      run: grep "Caused an ERROR" output/build/logs/*
    
#     - name: Check coverage tolerance
#       if: ${{ steps.ante_test_result.outputs.lineRate < 0.9 }}
#       uses: actions/github-script@v3
#       with:
#         script: |
#           core.setFailed('Coverage test below tolerance')

  
#     - name: ant_collect_results
#       run: grep "Caused an ERROR" output/build/logs/*
      
