name: CI 6 0 53

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 6
      uses: actions/setup-java@v1
#      uses: joschi/setup-jdk@v2
      with:
        java-version: '6'

    - name: build java
      run: java -version
      
    - name: build Ant
      run: ant -version
