name: CI 6 0 53

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 6
    - uses: joschi/setup-jdk@v2
      with:
        java-version: '6' # The OpenJDK version to make available on the path
        architecture: 'x64' # defaults to 'x64'  

    - name: build java
      run: java -version
      
    - name: build Ant
      run: ant -version
