name: CI 6 0 53

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup jdk 6
      uses: actions/setup-java@v1
#      uses: joschi/setup-jdk@v2
      with:
        java-version: '6'

    - name: build java
      run: java -version
    
    - name: donwload ant 9
      run: curl https://downloads.apache.org/ant/binaries/apache-ant-1.9.15-bin.zip --output ant9.zip

    - name: unzip ant 9
      run: unzip ant9.zip && pwd

    - name: ant home check 1
      run: echo $ANT_HOME && ls $ANT_HOME
#     - name: update ant home
#       run:  export ANT_HOME=/home/runner/apache-ant-1.9.15

    - name: update ant version to 1.9.15
      run:  sudo cp -a apache-ant-1.9.15/. $ANT_HOME
      #run:  mv apache-ant-1.9.15 $ANT_HOME

    - name: ant home check 2
      run: echo $ANT_HOME && ls $ANT_HOME

    - name: build Ant
      run: ant -version

#     - name: download libraries
#       run: curl https://support-delivery.s3.amazonaws.com/tomcat-build-libs.tar.gz --output tomcat-build-libs.tar.gz
      
#     - name: extract libs
#       run: tar -zxf tomcat-build-libs.tar.gz && ls tomcat-build-libs

    - name: download libraries
      run: curl https://support-delivery.s3.amazonaws.com/tomcat6-build-libs-.zip --output tomcat6-build-libs-.zip
      
    - name: extract libs
      run: unzip tomcat6-build-libs-.zip && ls tomcat-build-libs

    - name: update libs in property file
      run:  sed 's:base.path=${user.home}/tomcat-build-libs:base.path=/home/runner/work/TOMCAT_6_0_53-TT/TOMCAT_6_0_53-TT/tomcat-build-libs:' build.properties.default

    - name: check 4
      run: ls /home/runner/work/TOMCAT_6_0_53-TT/TOMCAT_6_0_53-TT/tomcat-build-libs
    
    - name: build ant
      run: ant
